### ISSUE TITLE
Invite expired, put new invite

### ISSUE THREAD

**Issue by sairam4123** [ShivangYT/Tic-Tac-Toe-Discord.py#1]
https://discord.gg/sgY2cyk this expired put a new invite in readme.md

**Comment by shivangrathore** [comment]
Thanks for telling me :)

**Comment by sairam4123** [comment]
Not yet updated, lel.

**Comment by sairam4123** [comment]
still?

**Comment by Tubbus** [comment]
The link is still invalid lmao
